# Generated by Django 5.1.5 on 2025-01-22 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meetlink", "0005_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="call",
            name="interpreter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interpreter_calls",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Interprete",
            ),
        ),
        migrations.AlterField(
            model_name="call",
            name="responsible",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responsible_calls",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responsável",
            ),
        ),
    ]
