# Get All Calls

GET http://localhost:8000/api/calls/

### Get All Calls

POST http://localhost:8000/api/calls/

### Get All Calls

POST http://localhost:8000/api/calls/3/insert_manager/
Content-Type: application/json

{
    "manager_id": 123
}

###

POST http://localhost:8000/api/calls/{id}/finish/

###